export const PAGE = {
  index: 'if-react',
  login: 'login',
  hotelsPage: 'hotels',
  review: 'review',
  destination: 'destination',
  about: 'About',
  work: 'How-Triphouse-works',
  careers: 'Careers',
  privacy: 'Privacy',
  terms: 'Terms',
  types: 'Property-types',
  guestHouses: 'Guest-houses',
  hotels: 'Hotels',
  apartments: 'Apartments',
  villas: 'Villas',
  holidayHomes: 'Holiday-homes',
  hostels: 'Hostels',
  support: 'Support',
  contact: 'Contact-Customer-Service',
  faq: 'FAQ',
  stays: 'stays',
  attractions: 'attractions',
};

export const PATH = {
  index: `/${PAGE.index}`,
  login: `/${PAGE.login}`,
  hotelsPage: `/${PAGE.hotelsPage}`,
  review: `/${PAGE.review}`,
  destination: `/${PAGE.destination}`,
  about: `/${PAGE.about}`,
  work: `/${PAGE.work}`,
  careers: `/${PAGE.careers}`,
  privacy: `/${PAGE.privacy}`,
  terms: `/${PAGE.terms}`,
  types: `/${PAGE.types}`,
  guestHouses: `/${PAGE.guestHouses}`,
  hotels: `/${PAGE.hotels}`,
  apartments: `/${PAGE.apartments}`,
  villas: `/${PAGE.villas}`,
  holidayHomes: `/${PAGE.holidayHomes}`,
  hostels: `/${PAGE.hostels}`,
  support: `/${PAGE.support}`,
  contact: `/${PAGE.contact}`,
  faq: `/${PAGE.faq}`,
  stays: `/${PAGE.stays}`,
  attractions: `/${PAGE.attractions}`,
};
